# Generated by Django 6.1.1 on 2026-09-09 12:48

import greeter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя, введённое пользователем на главной странице', max_length=100, validators=[greeter.models.validate_not_blank])),
            ],
        ),
    ]
